name: Expdamage
version: '${project.version}'
main: be.chenko.expdamage.Expdamage
api-version: 1.18
authors: [ chenko ]
description: The player receives damage when earning exp
website: https://www.chenko.be
permissions:
  expdamage.exempt:
    default: false
    description: Players with this permission will not take damage from exp orbs.
